language: ruby

rvm:
  - 1.9.3

env: NO_COVERAGE=true

bundler_args: --without development production

before_script:
  - psql -c 'create database saimoe2_test;' -U postgres
  - bundle exec rake db:migrate

notifications:
  email:
    - gerjomarty@anientity.co.uk